#!/bin/bash
#SBATCH --partition=gpunodes
#SBATCH --cpus-per-task=4
#SBATCH --mem=100G
#SBATCH --gres=gpu:1
#SBATCH --time=3:00:00
#SBATCH --job-name=irgan
#SBATCH --output=./outs/outputs/slurm-%j.out
#SBATCH --error=./outs/errors/slurm-%j.err


srun python train.py \
    --dataroot ./datasets/KAIST \
    --name KAIST_IRGAN \
    --model IRGAN \
    --direction BtoA \
    --tevnet_weights ./tev-out/KAIST/epoch_60.pth \




